### ISSUE TITLE
Where can I download MinDAEC ?

### ISSUE THREAD

**Issue by zuowanbushiwo** [lovemefan/Paraformer-webserver#1]
`pip install MinDAEC`
```
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
ERROR: Could not find a version that satisfies the requirement MinDAEC (from versions: none)
ERROR: No matching distribution found for MinDAEC
```

**Comment by lovemefan** [comment]
This project did not use the package MinDAEC,  Can you give more details when you meet this error

**Comment by zuowanbushiwo** [comment]
https://github.com/lovemefan/Paraformer-webserver/blob/v2.0/requirements.txt#L84  need this wheel?

**Comment by lovemefan** [comment]
> 

it's my mistake, this requirements need install with `pip install -r requirements.txt -f https://modelscope.oss-cn-beijing.aliyuncs.com/releases/repo.html` from modelscope . and it only support linux

**Comment by zuowanbushiwo** [comment]
ok,thanks!
